// POLLS ACTIONS
export const LOAD_MORE_START = 'LOAD_MORE_START'
export const LOAD_MORE_FINISH = 'LOAD_MORE_FINISH'
export const LOAD_DATA_START = 'LOAD_DATA_START'
export const LOAD_DATA_FINISH = 'LOAD_DATA_FINISH'
export const UPDATE_POLL_STATE = 'UPDATE_POLL_STATE'
